### ISSUE TITLE
Unable to unpack PSB from [ANIM] Joushi no Oku-san no Yokkyuu Fuman o Kaishou Sasete, Mi mo Kokoro mo Netoru Hanashi

### ISSUE THREAD

**Issue by xxxbagxx** [UlyssesWu/FreeMote#83]
i am trying to unpack some PSBs from the game but get this error and not able to find the psb key, if there is.

FreeMote PSB Decompiler
by Ulysses, wdwxy12345@gmail.com
15 Plugins Loaded.

Decompiling: MMisa100
FreeMote.PsbBadFormatException: Can not find Names segment, Dullahan load failed
   at FreeMote.Psb.PSB.LoadFromDullahan(Stream stream, Int32 detectSize, Nullable`1 namePosition)
   at FreeMote.Psb.PSB.DullahanLoad(Stream stream, Int32 detectSize)
   at FreeMote.PsBuild.PsbDecompiler.Decompile(String path, PSB& psb, Dictionary`2 context, PsbType psbType)
   at FreeMote.PsBuild.PsbDecompiler.DecompileToFile(String inputPath, PsbExtractOption extractOption, PsbImageFormat extractFormat, Boolean useResx, Nullable`1 key, PsbType type, Dictionary`2 contextDic)
   at FreeMote.Tools.PsbDecompile.Program.Decompile(String path, Boolean keepRaw, PsbImageFormat format, Nullable`1 key, PsbType type, Dictionary`2 context)
Done.

attached are the PSBs. Hope you can help me out
[PSBs.zip](https://github.com/UlyssesWu/FreeMote/files/8873265/PSBs.zip)

**Comment by UlyssesWu** [comment]
Encypted PSB. Find the key and use `PsbDecompile -k xxx mmisa100.psb` to unpack, or use `EmtConvert -k xxx mmisa100.psb` to decrypt and then view them in FreeMoteViewer.

Usually you just find the key by yourself. But for this time, key = 1195030893

**Comment by xxxbagxx** [comment]
thank you for your help.  However may i know how to find the psb key?

**Comment by UlyssesWu** [comment]
You may find it in emotedriver dll.
